/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}', './sidepanel.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        md: {
          gray: {
            50: '#f8f9fb',
            100: '#f1f2f5',
            200: '#e4e6eb',
            300: '#c9cdd4',
            400: '#a4a9b3',
            500: '#808690',
            600: '#636971',
            700: '#484d54',
            800: '#2e3238',
            900: '#1a1d21',
          },
          blue: {
            50: '#eef3ff',
            100: '#dce6ff',
            200: '#b9ceff',
            300: '#96b5ff',
            400: '#739dff',
            500: '#2469f0',
            600: '#1d58cc',
            700: '#1647a8',
          },
          green: {
            50: '#eaf6ef',
            100: '#d5edd9',
            200: '#abdbbe',
            300: '#81c9a3',
            400: '#57b788',
            500: '#1b8a4b',
            600: '#16753f',
            700: '#116033',
          },
          amber: {
            50: '#fef4e4',
            100: '#fde9c9',
            200: '#fbd293',
            300: '#f9bc5d',
            400: '#f7a527',
            500: '#c47a1a',
            600: '#a86615',
            700: '#8c5210',
          },
          red: {
            50: '#fcecee',
            100: '#f9d9dd',
            200: '#f3b3bb',
            300: '#ed8d99',
            400: '#e76777',
            500: '#cc3340',
            600: '#ad2b36',
            700: '#8e232c',
          },
          purple: {
            50: '#f2ebfa',
            100: '#e5d7f5',
            200: '#cbafeb',
            300: '#b187e1',
            400: '#975fd7',
            500: '#7b43c2',
            600: '#6939a5',
            700: '#572f88',
          },
          teal: {
            50: '#e6f5f2',
            100: '#ccebe5',
            200: '#99d7cb',
            300: '#66c3b1',
            400: '#33af97',
            500: '#0d7c6b',
            600: '#0b695b',
            700: '#09564b',
          },
        },
        /* ── shadcn/ui semantic colors ── */
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      fontFamily: {
        md: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      fontSize: {
        'md-xs': ['11px', '16px'],
        'md-sm': ['12px', '18px'],
        'md-base': ['13px', '20px'],
        'md-md': ['14px', '22px'],
        'md-lg': ['15px', '24px'],
        'md-xl': ['16px', '26px'],
        'md-2xl': ['18px', '28px'],
      },
      borderRadius: {
        md: '6px',
        'md-lg': '8px',
      },
      boxShadow: {
        'md-panel': '0 0 0 1px rgba(0,0,0,.04), 0 8px 32px rgba(0,0,0,.12)',
        'md-card': '0 0 0 1px rgba(0,0,0,.04), 0 1px 3px rgba(0,0,0,.06)',
        'md-dropdown': '0 4px 16px rgba(0,0,0,.14)',
        'md-float': '0 2px 8px rgba(0,0,0,.15)',
      },
      spacing: {
        'md-0.5': '2px',
        'md-1': '4px',
        'md-1.5': '6px',
        'md-2': '8px',
        'md-3': '12px',
        'md-4': '16px',
        'md-5': '20px',
        'md-6': '24px',
        'md-8': '32px',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'zoom-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        /* ── shadcn/ui keyframes ── */
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'collapsible-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        'collapsible-up': {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: '0' },
        },
        'caret-blink': {
          '0%,70%,100%': { opacity: '1' },
          '20%,50%': { opacity: '0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.15s ease-out',
        'zoom-in': 'zoom-in 0.15s ease-out',
        'slide-up': 'slide-up 0.15s ease-out',
        /* ── shadcn/ui animations ── */
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'collapsible-down': 'collapsible-down 0.2s ease-out',
        'collapsible-up': 'collapsible-up 0.2s ease-out',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
