"use strict";var __morbis_feature=(()=>{var d=Object.defineProperty;var S=Object.getOwnPropertyDescriptor;var E=Object.getOwnPropertyNames;var T=Object.prototype.hasOwnProperty;var k=(n,e)=>{for(var o in e)d(n,o,{get:e[o],enumerable:!0})},I=(n,e,o,t)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of E(e))!T.call(n,i)&&i!==o&&d(n,i,{get:()=>e[i],enumerable:!(t=S(e,i))||t.enumerable});return n};var P=n=>I(d({},"__esModule",{value:!0}),n);var C={};k(C,{fetchFileFromUrl:()=>w,injectSharedCSS:()=>g,numberToWords:()=>B,safeFetch:()=>a,showErrorToast:()=>v,toggleProcessingState:()=>b});var h=!1;function g(){if(h||document.getElementById("ext-batch-shared-style"))return;let n=document.createElement("link");n.id="ext-batch-shared-style",n.rel="stylesheet",n.href=chrome.runtime.getURL("features/shared/batch-ui.css"),document.head.appendChild(n),h=!0,console.log("[SharedUtils] CSS injected")}async function a(n,e={},o=2){try{let t=new AbortController,i=setTimeout(()=>t.abort(),3e4),c=await fetch(n,{...e,signal:t.signal});return clearTimeout(i),c}catch(t){if(o>0&&t.name!=="AbortError")return await new Promise(i=>setTimeout(i,1e3)),a(n,e,o-1);throw t}}async function w(n,e){let o=await a(n,{method:"GET",mode:"cors",credentials:"omit"});if(!o.ok)throw new Error(`HTTP ${o.status}`);let t=await o.blob();return new File([t],e,{type:t.type})}async function j(n,e){try{let o=await w(n,e),t=URL.createObjectURL(o);f(t,e,()=>URL.revokeObjectURL(t))}catch(o){console.error("[Preview] Fetch error:",o),f(n,e)}}function f(n,e,o=null){let t=document.getElementById("ext-inline-preview-modal");t&&t.remove();let i=e.toLowerCase().split(".").pop()||"",c=i==="pdf",x=["jpg","jpeg","png","gif","webp"].includes(i),r=document.createElement("div");r.id="ext-inline-preview-modal";let y=c?`<iframe id="ext-inline-preview-iframe" src="${n}"></iframe>`:x?`<img id="ext-inline-preview-img" src="${n}" loading="lazy">`:`
        <div class="ext-inline-preview-error">
          <div style="font-size: 18px; color: #ef4444;">\u{1F4C4}</div>
          <div>Format tidak didukung</div>
        </div>`;r.innerHTML=`
    <div class="ext-inline-preview-header">
      <span class="ext-inline-preview-filename" title="${e}">${e}</span>
      <button class="ext-inline-preview-btn" id="ext-preview-newtab">Tab Baru</button>
      <button class="ext-inline-preview-close" id="ext-preview-close">\u2715</button>
    </div>
    <div class="ext-inline-preview-content">
      ${y}
    </div>`,document.body.appendChild(r),r.focus();let m=document.getElementById("ext-preview-close"),p=document.getElementById("ext-preview-newtab"),s=()=>{o&&o(),r.remove()};m&&(m.onclick=s),p&&(p.onclick=()=>{window.open(n,"_blank"),s()}),r.onclick=l=>{l.target===r&&s()},document.onkeydown=l=>{l.key==="Escape"&&s()}}function b(n,e){n.forEach(o=>{let t=document.getElementById(o);t&&(t.style.opacity=e?"0.5":"1",t.style.cursor=e?"not-allowed":"pointer")})}function v(n){let e=document.createElement("div");e.style.cssText=`
    position: fixed; top: 20px; right: 20px;
    background: #ef4444; color: white; padding: 12px 20px;
    border-radius: 6px; z-index: 10001; font-weight: 500;
    box-shadow: 0 4px 12px rgba(239,68,68,0.4);
  `,e.textContent=`Error: ${n}`,document.body.appendChild(e),setTimeout(()=>e.remove(),5e3)}window.SharedBatchUtils={injectSharedCSS:g,safeFetch:a,showInlinePreviewSafe:j,toggleProcessingState:b,showErrorToast:v};var u=["","satu","dua","tiga","empat","lima","enam","tujuh","delapan","sembilan","sepuluh","sebelas"];function B(n){let e=Math.abs(Math.trunc(Number(n)));if(!Number.isFinite(e))return String(n);let o=t=>t<12?u[t]:t<20?u[t-10]+" belas":t<100?(t<20?"":o(Math.trunc(t/10))+" puluh "+u[t%10]).trim():"";if(e===0)return"nol";if(e<100)return o(e);if(e<1e3){let t=e%100;return(e<200?"seratus":o(Math.trunc(e/100))+" ratus")+(t?" "+o(t):"")}return String(e)}console.log("[SharedUtils] Loaded");return P(C);})();
